### PR TITLE
[d3d8] Fix tests output not being displayed

### PR DESCRIPTION
**Pull request by WinterSnowfall**
Fix a small derp. While it is essentially a d3d8 triangle, the initial part of it (namely the d3d8 tests and stats) rely on outputting to a command prompt. Tested it with `gui_app: false` on both Windows and Linux and it does what it's supposed to, at least when using mingw. Not sure about MSVC, but it _should_ behave similarly.

### CODE REVIEW

**Comment by pchome** [comment]
https://mesonbuild.com/Reference-manual_functions.html#arguments10
`gui_app`
1. > default = false
2. > DEPRECATED in 0.56.0

`win_subsystem`
1. > default = 'console'
2. > (since 0.56.0)

So (I guess) just remove `gui_app: false` and forget.

**Comment by WinterSnowfall** [comment]
> So (I guess) just remove `gui_app: false` and forget.

Thank you, that indeed seems to be the default, even when using WinMain. I'll forget about it now... unless MSVC says otherwise. It might complain, since `gui_app: true` is kind of expected here, but the console output is more important than the actual triangle in this case.

**Comment by WinterSnowfall** [comment]
Ok, if I'm reading this right, adding a dummy `int main(int, char**)` should make MSVC happy with `gui_app: false`/in default mode. Unfortunately I have no way to test if this actually works in MSVC, and mingw simply doesn't care in this case (it's rather silly anyway, but whatever).

**Comment by pchome** [comment]
Maybe separate gui and non-gui tests, like done in `d3d11/*`? It shouldn't be all-in-one.

[out of scope]
if important to stay on current minimum meson version (`0.49`) for a while maybe worth to check `meson.version()` and use either `gui_app` or `win_subsystem` where needed.

**Comment by WinterSnowfall** [comment]
> Maybe separate gui and non-gui tests, like done in `d3d11/*`? It shouldn't be all-in-one.

There's no standard here (they're just tests after all), and to be honest when I wrote them the idea was **_to have them be_** all in one for d3d8. It makes things a whole lot simpler IMHO.

**Comment by pchome** [comment]
Ah yes, "not have to be" I mean.
Sure your choice, but my IMHO:
it would be cool if all tests was consistent/same across dx versions. You know, like "hello world" or an algorithm implementation in different languages. Then just bundle all list in shell script and call with `--d3d*` parameter ...

Anyway, I'm going to play with this test later, will see if it breaks for me.

**Comment by pchome** [comment]
The test is ok with `gui_app` removed on linux mingw, but confusing a bit:
<details><summary>rant</summary>

* run via launcher w/o console output
  * it _wait_ 
  * then show the triangle test window
* run via terminal
  * output to terminal
  * then show the triangle test window
* run via terminal w/ vd `$ wine explorer.exe /desktop=test,1920x1080 d3d8-triangle.exe`
  * output to wine console window
  * then show the triangle test in separate window
  * only unrelated messages are in linux terminal

###### _I like the last one, because I can switch to console window and read the output (before everything is gone) while the triangle test trashing my CPU/GPU. For better effect I'd recommend disabling vsync. jk_

bonus: `$ DXVK_LOG_LEVEL=info DXVK_LOG_PATH=none wine d3d8-triangle.exe` 

</details>

**EDIT**: my fault, it was confusing for me because I never used other methods than bash scripts or vd configured via winecfg (similar results).
Setting up virtual desktop in winecfg currently broken (wine 8.12 +/-), so I used alternative, which somehow behave differently.

**Comment by WinterSnowfall** [comment]
Thanks for testing. It's a bit weird that you're seeing different behaviors. I tested it on:

- Windows, double clicking - creates a command prompt window for the test output and a separate window for the triangle (that's indended)
- Windows, launched via command line - same as above, but outputs directly to the existing command line
- Wine, double clicking - creates a `wineconsole` window for the text output and a separate window for the triangle (matches Windows behavior really, but it's bit more janky in Wine)
- Wine, launched via terminal emulator - same as above, but uses the terminal for output (<--- use this option for best results)

That's sort of what I intended it to do, anyway, as seeing the triangle window at the end means you have successfully (at least to a non-critical degree) passed through the test gauntlet.

If anyone can test if the "MSVC hack" works, I'd appreciate it.

P.S.: And yes, you're really meant to slience all other loggers if you want something clean. All tests use std::cout, no fancy loggers. And while they do obviously work with dxvk, you can run them on any d3d8 implementation out there.

**Pull request closed without merging**
